# Maestro Configuration
# This file contains configuration options for Maestro tests

# Application ID for the app under test
appId: com.subnext.tipcalcbillsplit

# Default platform (can be overridden with --platform flag)
# platform: android

# Screenshot configuration
screenshots:
  enabled: true
  outputDir: screenshots

# Test configuration
test:
  timeout: 30000  # 30 seconds
  retries: 2
