name: Build and Submit to Google Play

on:
  workflow_dispatch:
    inputs:
      build_profile:
        description: 'EAS Build Profile'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - preview
      submit_to_google_play:
        description: 'Submit to Google Play after build'
        required: true
        default: true
        type: boolean
      version_bump:
        description: 'Version bump type'
        required: false
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - none

jobs:
  build-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Bump version
        if: ${{ github.event.inputs.version_bump != 'none' }}
        run: yarn version --${{ github.event.inputs.version_bump }} --no-git-tag-version

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android app
        run: eas build --platform android --profile ${{ github.event.inputs.build_profile }} --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Submit to Google Play
        if: ${{ github.event.inputs.submit_to_google_play == 'true' }}
        run: eas submit --platform android --latest --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_GOOGLE_SERVICE_ACCOUNT_KEY_BASE64: ${{ secrets.EAS_GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }}
