name: Expo Build Test
on:
  push:
    branches:
      - develop
jobs:
  publish:
    name: Expo Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: pnpm install
      - run: pnpm test
      - name: Publish update
        run: eas update --auto --non-interactive
