name: Expo Publish
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - uses: expo/expo-github-action@v8
        with:
          expo-version: 5.x
          token: ${{ secrets.EXPO_TOKEN }}
      - uses: fregante/setup-git-user@v2
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: pnpm install
      - name: Install release-it
        run: pnpm add release-it
      - run: pnpm run release-it --ci --minor
      - run: expo build:android --no-wait
      - run: expo build:ios --no-wait
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
