name: Expo Build Test
on:
  push:
    branches:
      - develop
jobs:
  publish:
    name: Expo Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm exec expo login --token ${{ secrets.EXPO_TOKEN }}
      - run: pnpm test
      - run: pnpm exec expo publish
